sudo: false
dist: trusty
language: cpp
services:
- docker
script:
#- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t uofscphysics/base -f build/Dockerfile.base build/.
- docker build -t uofscphysics/python -f build/Dockerfile.python build/.
- docker images -a
